farcaster-project/farcaster-core

- src/blockchains/bitcoin.rs
- src/blockchains/mod.rs
- src/blockchains/monero.rs
- src/negotiation.rs
- src/roles.rs
`Buy` and `Sell` help to create `Offer`s in an easy and convenient way. They are used by the `maker` and are design based on buying and selling arbitrating assets for accordant ones.
> Add Buy and Sell helper in negotiation

- Cargo.toml
- src/bitcoin/mod.rs
- src/bitcoin/transaction/mod.rs
- src/blockchain.rs
- src/consensus.rs
- src/datum.rs
- src/lib.rs
- src/monero/mod.rs
- src/negotiation.rs
- src/role.rs
- src/transaction.rs
- tests/run.sh
- tests/transactions.rs
Add public offer serialization based on introducting Farcaster strict encoding and Blockchain related strict encoding. Farcaster encoding wraps values from specific blockchain consensus encoding, as proposed in https://github.com/h4sh3d/RFCs/blob/rfc-10/10-public-offer.md.
> Negotiation public offer serialization

- core/src/negotiation.rs
Light alternative to #18 (without `FromStr` impl.)
> Add strict encoding for public offer

- chains/tests/negotiation.rs
- core/src/blockchain.rs
- core/src/negotiation.rs
The generic implementation:
```rust
impl<T: Asset> Encodable for T {
fn consensus_encode<W: io::Write>(&self, writer: &mut W) -> Result<usize, io::Error> {
self.to_u32().consensus_encode(writer)
}
}
```
It was generating bad error message as if Asset is implemented on a type `Encodable` and `Decodable` is too. This has to be fixed.
Field names in `Offer` as been improved as asked in #25
> Remove generic Asset Encodable/Decodable and disambiguates asset from amount of assets

- chains/src/bitcoin/mod.rs
- chains/src/monero/mod.rs
- chains/src/pairs/btcxmr.rs
- core/src/crypto.rs
- core/src/protocol_message.rs
- core/src/role.rs
- core/src/swap.rs
Commit trait was implemented on each chain, meaning every chain can choose what to use as a hash, now the commit is under the context, a commit/reveal scheme is define per blockchain pairs.
> Move commit from Arb/Acc to Swap

- .github/workflows/ci.yml
- src/chain/bitcoin/transaction/mod.rs
- src/consensus.rs
- src/negotiation.rs
- tests/rpc/mod.rs
This temporarily remote ` -- -D warnings` on clippy checks so warnings are not considered as errors anymore. This allow to have CI pass and warnings will be resolved later.
> Relax clippy errors, fix clippy hard errors

- Cargo.toml
- run-rpc-tests.sh
- src/blockchain.rs
- src/bundle.rs
- src/chain/bitcoin/address.rs
- src/chain/bitcoin/amount.rs
- src/chain/bitcoin/fee.rs
- src/chain/bitcoin/mod.rs
- src/chain/bitcoin/timelock.rs
- src/chain/bitcoin/transaction/mod.rs
- src/chain/monero/mod.rs
- src/chain/pairs/btcxmr.rs
- src/consensus.rs
- src/crypto.rs
- src/events.rs
- src/negotiation.rs
- src/protocol_message.rs
- src/role.rs
- src/swap.rs
- src/syncer.rs
Rework of `CanonicalBytes`, `Encodable/Decodable` traits and `strict_encoding` in core.
This fix #27 and fix #26 in the previous PR.
> Rework general handling of encoding in core

- src/negotiation.rs
- src/role.rs
Fix #60, TradeRole is more accurate.
> Rename NegotiationRole to TradeRole

- Cargo.toml
Pin versions to: 
```toml
strict_encoding = "=1.2.3"
strict_encoding_derive = "=1.0.0"
```
so `core` and `node` compiles with the current set of dependencies.
> Pin strict_encoding version and derive to comply with the node

- src/negotiation.rs
Implement `Hash` on `Offer` through `consensus::serialize` (which is a slow implementation of Hash but allow to not bound every types with `: Hash`) and `PublicOffer` with `derive(Hash)`.
> Add hash impl on public offer

- src/negotiation.rs
Change derivation into implementation based on serialization for `PublicOffer`
> Change PublicOffer implementation, based on encoding now

- src/negotiation.rs
See https://doc.rust-lang.org/std/hash/trait.Hash.html#hash-and-eq for the property that must old when `Hash` and `Eq` are implemented manually.
> Make sure Hash and Eq property holds

- Cargo.toml
- src/protocol_message.rs
Fix #47 
Add encoding for lightning messages on protocol messages with
```rust
use lightning_encoding::{Strategy, strategies::AsStrict};
impl<Ctx> Strategy for BuyProcedureSignature<Ctx>
where
Ctx: Swap,
{
type Strategy = AsStrict;
}
```
> Add lightning encoding on protocol messages

- Cargo.toml
- src/blockchain.rs
- src/bundle.rs
- src/chain/bitcoin/fee.rs
- src/chain/bitcoin/timelock.rs
- src/crypto.rs
- src/lib.rs
- src/negotiation.rs
- src/protocol_message.rs
- src/role.rs
- src/script.rs
- src/swap.rs
- src/transaction.rs
Fix #88 
Implement `fmt::Display` for major structures in the lib.
This introduces display and serde on the structure where it is easily possible to do so. More refactor must be done to extend it's support, or enforce serde everywhere for having Offer, PublicOffer and other messages as currently designed.
> Implement traits for major structures

- src/bitcoin/segwitv0/mod.rs
Required for [aligning node](https://github.com/farcaster-project/farcaster-node/pull/60) with [internal variation of bitcoin implementation](https://github.com/farcaster-project/farcaster-core/pull/86) and [flattened modules](https://github.com/farcaster-project/farcaster-core/pull/96).
> Change FromStr implementation target for SegwitV0

- src/transaction.rs
Fix #108 
Rename `TxId` into `TxLabel` to disambiguating from bitcoin crate Txid.
> Rename TxId into TxLabel

- src/bitcoin/fee.rs
- src/blockchain.rs
- tests/wallet.rs
Fix #106 
`FromStr` and `Display` are consistent now and use `bitcoin::Amount` internal parsing/display.
> Rework FromStr and Display for SatPerVByte

- Cargo.toml
- README.md
- src/bitcoin/mod.rs
- src/bitcoin/segwitv0/mod.rs
- src/bitcoin/taproot/mod.rs
- src/blockchain.rs
- src/crypto.rs
- src/lib.rs
- src/role.rs
- src/swap/btcxmr.rs
- src/swap/mod.rs
- tests/bundles.rs
- tests/protocol.rs
- tests/wallet.rs
> Bootstrap taproot and new key manager

- .github/workflows/test.yml
- Cargo.toml
- contrib/run-rpc-tests.sh
- src/bitcoin/segwitv0/buy.rs
- src/bitcoin/segwitv0/cancel.rs
- src/bitcoin/segwitv0/lock.rs
- src/bitcoin/segwitv0/mod.rs
- src/bitcoin/segwitv0/punish.rs
- src/bitcoin/segwitv0/refund.rs
- src/bitcoin/timelock.rs
- src/role.rs
- src/script.rs
- src/transaction.rs
- tests/protocol.rs
- tests/rpc/mod.rs
- tests/transactions.rs
Work in progress, modify the segwit v0 implementation and complete the tx management by extracting the witness from buy (todo for refund).
Still need a lot of tests everywhere for the transactions implementation, to be sure that the template verification is done correctly, that the witness extraction works, etc.
> Modify segwit0 and extract witness

- Cargo.toml
- tests/rpc/mod.rs
Fix RPC for new version. Rewriting some version in Cargo.toml, this
should not change how deps are managed.
> Update Bitcoin and Bitcoincore RPC deps

- src/crypto.rs
- src/monero.rs
- src/protocol_message.rs
- src/role.rs
- tests/wallet.rs
Based on #139 
Add code to generate accordant address by hand in a test and add support in core to do the same with data coming from the protocol.
> Manage accordant address

- Cargo.toml
required for downstream bitcoin 0.27 bumps: https://github.com/farcaster-project/farcaster-node/pull/120
> bump lnp dependencies

- src/crypto/dleq.rs
- src/swap/btcxmr.rs
our protocol messages are slightly too large for the frame limit (`65815` bytes vs `65535 + 18 + 16 = 65569` bytes) imposed by [rust-internet2::transport](https://github.com/internet2-org/rust-internet2/blob/master/src/transport/mod.rs#L35-L47) (i.e. [BOLT](https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#type-length-value-format)), and these pubkeys can be reconstructed from commitments anyway. This shaves off `65` bytes and thus gets us a bit closer ;)
> remove public keys from DLEQ proof

- .github/workflows/build.yml
- .github/workflows/create-release.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/release-to-crates-io.yml
- .github/workflows/test.yml
- CHANGELOG.md
- RELEASING.md
- dprint.json
Use in release-to-crates-io
```yaml
workflow_run:
workflows: ["Create release"]
types:
- completed
```
to trigger publish after release.
> Update shared workflows and add publish after release

- .github/workflows/release-to-crates-io.yml
Only run release to crates.io if create release status is success
> Fix CI workflow run

- CHANGELOG.md
- src/monero.rs
- src/role.rs
- src/transaction.rs
- tests/protocol.rs
- tests/wallet.rs
Rename `recover_accordant_assets`, fix Monero network conversion from blockchain network, and add strict encode + decode for `TxLabel`.
> Fix some issues

- CHANGELOG.md
- Cargo.toml
- src/negotiation.rs
Use base58 with checksum for public offers print and parse functions.
> Change public offer format for display and from string

- Cargo.toml
Problematic version has been yanked, pin is unecessary now.
> Remove pin for parity backend crypto

- CHANGELOG.md
- src/negotiation.rs
This adds some tests on public offer serialization and happened `Offer` before the base58 string.
> Add prefix `Offer` to serialized public offer

- CHANGELOG.md
- src/hash.rs
- src/lib.rs
- src/negotiation.rs
- src/swap.rs
Implement manually `serde` for hash ids so they serialize as string containing the full hex formatted content of the hash.
> Reimplement serde for `SwapId`, `OfferId` and `PublicOfferId`

- CHANGELOG.md
- src/bitcoin/fee.rs
- src/blockchain.rs
Fix #172 
Use custom struct enum with clear name regarding inclusive bounds and add specific bound checks method on fee strategy type.
> Remove std Range from fee strategy

- CHANGELOG.md
- src/bitcoin/segwitv0.rs
- src/bitcoin/taproot/mod.rs
- src/bitcoin/timelock.rs
- src/blockchain.rs
- src/negotiation.rs
- src/role.rs
Fix #186
Implements `fmt::Display` on `Offer` along other types. Change some `ToString` impl with proper `Display` for better genericity.
~Relax clippy warnings and add msrv in case of new breaking rules.~
> Add Display offer implementation

- CHANGELOG.md
- src/monero.rs
- src/negotiation.rs
- Add "monero" and "xmr" variants for Monero FromStr impl
- Fix Display implementation where it doesn't work outside of stdout
> Monero Display and FromStr

- CHANGELOG.md
- src/bitcoin/segwitv0.rs
For now we only use the `Bitcoin<SegwitV0>` struct and have `Bitcoin|bitcoin` FromStr is handy for the node.
After `Coin` is introduced for all blockchain and variant this code should not be used anymore. In the meantime it is better to have this for node.
> Add bitcoin variant for Bitcoin<Segwit> FromStr

- CHANGELOG.md
- Cargo.toml
Reverts the release in farcaster-project/farcaster-core#234 as it cannot be published on crates.io because of a git dependency.
> Revert "Release version 0.4.5"

- .github/workflows/test.yml
To avoid having issues with `latest` tag moving on our containers when we do updates we pin to current latest: `23.0`.
> Pin bitcoin-core version used in CI

- src/swap/btcxmr.rs
`ChildNumber` implementation of From/Into u32 cannot be used with the current `new` function, this fixes the decode method.
> fix: key manager consensus decodable implementation

- CHANGELOG.md
- Cargo.toml
- src/crypto/dleq.rs
This pull request is to fix the compilation errors of #212 in order to upgrade bitvec's dependencies to the latest version. I have done below modifications to crypto/dleq.rs:
- Modified the order of BitSlice's parameters accordingly with the latest version as it is expecting the following input format <u8, Lsb0>
- Removed unwrap() as already called in bitvec from_slice() function
> Fix bitvec dependencies

- src/bitcoin/fee.rs
- src/bitcoin/timelock.rs
- src/blockchain.rs
- src/negotiation.rs
- src/protocol.rs
- src/protocol/message.rs
- src/transaction.rs
Based on https://github.com/farcaster-project/farcaster-core/pull/255
Fix #80, fix #178, fix #240
Adds serde on all useful remaining types.
> feat: add serde on missing structs

- src/bitcoin/segwitv0.rs
- src/bitcoin/taproot/mod.rs
- src/blockchain.rs
- src/crypto.rs
- src/protocol.rs
- src/protocol/message.rs
- src/role.rs
- src/swap/btcxmr.rs
- src/transaction.rs
- tests/wallet.rs
Based on #255
Diff starts at e287d1efee5ef0e2713d88de30ef74630a70f441.
Split the `Sign` trait to be more specific about requirements in `protocol` functions. Remove `Signatures` trait because it became useless after #255 refactor. Improve `Commit` trait.
> refactor: split crypto sign trait and clean crypto module

- src/bitcoin.rs
- src/blockchain.rs
- src/monero.rs
Fix #248
When reviewing #247 I missed the conversion flow, it should be `blockchain::Network` -> `btc|xmr::Network` and not the inverse. And the issue was not describing the problem correctly, sorry for that.
> fix: network conversions

- src/bitcoin/timelock.rs
Fix #182
Implement `From` for different types to easily construct timelocks from generic cli arguments in node.
> feat: impl timelock from

- Cargo.toml
- src/swap/btcxmr.rs
Fix #246
Temporary usage of bytes to convert between `secp256k1` and `*fun` libs, waiting next release to synchronize `secp256k1` again. See #268.
> chore: use crates.io secpfun, use bytes to convert types

- src/swap/btcxmr.rs
- tests/protocol.rs
Each swap-pair module should export fully defined types based on generic ones in root modules.
> feat: define concrete types in btcxmr modules

- src/swap/btcxmr.rs
- src/swap/btcxmr/message.rs
Add all protocol message under `btcxmr::message` module and other protocol types.
> feat: more type definition for btc/xmr swap

- CHANGELOG.md
- Cargo.toml
Codebase seems to be already compatible with Rust edition 2021.
> chore: update rust edition 2021

- .github/workflows/create-release.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/release-to-crates-io.yml
Update shared workflows, this should not change previous functionalities, but uses up-to-date GH Actions.
> ci: bump ci shared workflows to 1.2.0

- .github/workflows/test.yml
- Cargo.toml
- src/lib.rs
Introduce nightly feature to enable stmt_expr_attributes that fix nightly compilation
It sucks because the `Cargo.toml` got worst and it will also pollute node when released.
**When using nightly to compile the crate you must enable the `nightly` feature**
> fix: nightly compilation

- CHANGELOG.md
- Cargo.toml
- src/protocol/message.rs
- src/swap.rs
Remove unused dependency, _node_ doesn't use lightning encoding anymore for p2p messages.
> refactor: remove lightning encoding

- src/protocol/message.rs
Clean up the protocol message file by removing old bundle code that got commented on the last refactor.
> chore: remove unnecessary comments

- CHANGELOG.md
- README.md
- src/blockchain.rs
- src/consensus.rs
- src/crypto.rs
- src/hash.rs
- src/lib.rs
- src/protocol.rs
- src/role.rs
- src/swap/btcxmr.rs
- src/trade.rs
- tests/protocol.rs
- tests/trade.rs
`Offer` and `negotiation` are misleading as they are used to initialized a swap more than to negotiate a trade. To separate the current ambiguity we move completely to `trade` terminology to allow `negotiation` and `offer` to fulfill their roles later.
Also the negotiation is not part of the minimum stack and does not require to be inside _core_ (nor even _node_), this can be left to other implementations.
**EDIT**
`farcaster_core::negotiation` becomes `farcaster_core::trade`
`Offer` becomes `DealParameters`
`PublicOffer` becomes `Deal`
> refactor: move to trade terminology

- CHANGELOG.md
- src/trade.rs
Fixes #310
User can input any string, check that we have enough chars to split the str in two parts, otherwise it's not a deal.
> Fix: check len when parsing deals from str

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
- src/bitcoin/fee.rs
- src/blockchain.rs
Fix  #312
A new feature `fee_range` is added to the crate (disable by default) so we can remove the support in node and add it back when we want.
> Feat: add fee range under crate feature

- CHANGELOG.md
- src/bitcoin/fee.rs
- src/blockchain.rs
- src/swap/btcxmr.rs
- src/trade.rs
- tests/trade.rs
- tests/transactions.rs
Fix #117
This new unit allows fee under 1 sat per virtual byte.
> Refactor: change sat/vB to sat/kvB

- src/bitcoin/fee.rs
Some documentation hasn't been updated properly.
> Doc: fix missing renaming vByte to kvB

- CHANGELOG.md
- src/bitcoin/fee.rs
- tests/transactions.rs
We now account for the standard witness size (buy/cancel, refund may be a bit bigger) and compute/check the fee rate correctly.
> Fix: better fee calculation and check

- CHANGELOG.md
- src/bitcoin/segwitv0/funding.rs
> Feat: Derive strict encoding for funding transaction

- CHANGELOG.md
- src/lib.rs
Our wrapper `Uuid` can now be retrieved with `dealid.into()` and `swapid.into()`
> Feat: add from deal and swap ids for uuid

- CHANGELOG.md
- src/crypto/slip10.rs
- src/swap/btcxmr.rs
Derive account level keys on initialization.
This has the benefit of informationally segregating instantiated key manager.
Since the swap index is not mutable, every swap has to instantiate its own key manager. In order to informationally guarantee that each swap can only read and reach keys with its own swap index, derive the keys to the account index on key manager generation.
This is the last piece of the puzzle of the swap/wallet refactor that I discussed with @Lederstrumpf .
> Refactor(KeyManager): Don't persist master secret

- CHANGELOG.md
- src/bitcoin/segwitv0.rs
- src/protocol.rs
- src/script.rs
- tests/transactions.rs
Closes #254, swap role keys is more appropriate as this struct holds one public key per swap role.
> Refactor: rename DoubleKeys into SwapRoleKeys

- CHANGELOG.md
- src/protocol.rs
- src/protocol/message.rs
- src/swap/btcxmr/message.rs
- tests/protocol.rs
Closes #278
We don't need to have two peer message types for revealing parameters and proofs. The current node implementation group them in an enum under Alice and Bob, this enum containing the old reveal params and proof and had the swap id field twice. This fixes it and will simplify node's implementation.
> Refactor: unify protocol reveal params and proof messages
