Cargo.toml
src/blockchains/mod.rs
src/crypto.rs
src/instructions.rs
src/protocol.rs
src/roles.rs

Add more documentation and test protocol message to see if the interface is usable or not, for now looks good.

Document and test

---

.rustfmt.toml
chains/src/bitcoin/mod.rs
chains/tests/negotiation.rs
core/src/blockchain.rs
core/src/negotiation.rs
core/src/role.rs

We could use this? Feel free to propose a different one.
Rebase and fmt before merging

add .rustfmt.toml file

---

chains/src/pairs/btcxmr.rs
chains/tests/bundles.rs
core/src/bundle.rs
core/src/consensus.rs
core/src/crypto.rs
core/src/datum.rs
core/src/protocol_message.rs
core/src/role.rs

Implement commit/reveal logic and messages for Alice and Bob roles.

Implement commit/reveal for Alice and Bob

---

chains/src/bitcoin/fee.rs
chains/src/bitcoin/mod.rs
chains/src/bitcoin/transaction/buy.rs
chains/src/bitcoin/transaction/cancel.rs
chains/src/bitcoin/transaction/funding.rs
chains/src/bitcoin/transaction/lock.rs
chains/src/bitcoin/transaction/mod.rs
chains/src/bitcoin/transaction/punish.rs
chains/src/bitcoin/transaction/refund.rs
chains/src/monero/mod.rs
chains/src/pairs/btcxmr.rs
chains/tests/bundles.rs
core/src/blockchain.rs
core/src/consensus.rs
core/src/crypto.rs
core/src/lib.rs
core/src/negotiation.rs
core/src/protocol_message.rs
core/src/role.rs
core/src/transaction.rs

Rework the errors in `core`.
Based on #34, rebase and merge.

Core errors

---

src/chain/monero/tasks.rs

Fix formatting inconsistencies.

Format the code with cargo fmt

---

src/chain/bitcoin/address.rs
src/chain/bitcoin/amount.rs
src/chain/bitcoin/fee.rs
src/chain/bitcoin/mod.rs
src/chain/bitcoin/transaction/buy.rs
src/chain/bitcoin/transaction/funding.rs
src/chain/bitcoin/transaction/lock.rs
src/chain/bitcoin/transaction/mod.rs
src/chain/bitcoin/transaction/punish.rs
src/chain/bitcoin/transaction/refund.rs
tests/negotiation.rs
tests/transactions.rs

Remove unnecessary wrappers after merging both crates together.

Remove unnecessary wrappers

---

.github/dependabot.yml
.github/workflows/ci.yml
run-rpc-tests.sh
tests/rpc/mod.rs

Add CI with static analysis and tests and dependabot.

Add basic CI and dependabot config

---

.github/workflows/ci.yml
Cargo.toml
run-rpc-tests.sh
tests/rpc/mod.rs

Update service image

---

src/chain/pairs/btcxmr.rs

Add keyless variant for Wallet

---

Cargo.toml
src/consensus.rs
src/swap.rs

issue #48 documents other missing traits

add strict encoding and lightning encoding to swap_id

---

src/protocol_message.rs
tests/bundles.rs
tests/protocol.rs
tests/protocol_message.rs

Add swap id on protocol messages

---

src/blockchain.rs

Implements FromStr for FeePolitic

---

src/negotiation.rs

Fix swap role doc in negotiation

---

README.md
src/bitcoin/fee.rs
src/bitcoin/mod.rs
src/bitcoin/tasks.rs
src/bitcoin/timelock.rs
src/bitcoin/transaction.rs
src/blockchain.rs
src/bundle.rs
src/consensus.rs
src/crypto.rs
src/monero/mod.rs
src/monero/tasks.rs
src/negotiation.rs
src/protocol_message.rs
src/role.rs
src/script.rs
src/syncer.rs
src/transaction.rs

Improvements and new documentation for the crate.

Improve crate documentation

---

src/bitcoin/fee.rs
src/blockchain.rs
src/role.rs
tests/bundles.rs
tests/protocol.rs
tests/transactions.rs

Fix #110
Rename the enum and its variants.

Rename FeePolitic into FeePriority

---

src/syncer.rs

Fix encoding returned lenght

---

.github/workflows/analysis.yml
.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/test.yml
CHANGELOG.md
README.md
src/lib.rs

Other minor changes to prepare the first release.

Minor changes to prepare release

---

.github/workflows/analysis.yml
src/bitcoin/address.rs
src/bitcoin/fee.rs
src/bitcoin/mod.rs
src/bitcoin/segwitv0/funding.rs
src/bitcoin/segwitv0/lock.rs
src/bitcoin/segwitv0/mod.rs
src/bitcoin/transaction.rs
src/blockchain.rs
src/crypto.rs
src/lib.rs
src/protocol_message.rs
src/role.rs
src/swap/btcxmr.rs
src/syncer.rs
tests/bundles.rs
tests/protocol.rs

Set fail on warnings for clippy in CI again.

Fix clippy warnings

---

CHANGELOG.md
Cargo.toml
README.md

Release version 0.1.0

---

.github/workflows/test.yml
contrib/run-rpc-tests.sh
src/bitcoin/segwitv0/lock.rs
src/bitcoin/transaction.rs
tests/transactions.rs

Test with multi ins and outs for funding transaction

Improve funding tx tests

---

.github/workflows/test.yml
contrib/run-rpc-tests.sh
tests/rpc/mod.rs

Use the new container image. Connects to bitcoin-core with `.cookie` file and shared volume.

Update regtest CI

---

src/bitcoin/segwitv0.rs
src/bitcoin/taproot/mod.rs
src/bundle.rs
src/crypto.rs
src/monero.rs
src/protocol_message.rs
src/role.rs
src/swap/btcxmr.rs
tests/protocol.rs
tests/wallet.rs

Fix #135
Rename different types and variable names, try to be more comprehensive in the naming...

Renaming some traits & structs

---

src/swap/btcxmr.rs
tests/protocol.rs
tests/wallet.rs

Complete the implementation for leaking the Accordant blockchain secret spend key through Arbitrating encrypted signatures.

Add correct accordant secret spend management

---

src/consensus.rs
src/crypto/dleq.rs

Encoding/Decoding support for DLEQ

---

.github/workflows/build.yml
README.md

README says MSRV 1.54 for the lib, add a build in CI to make sure it stays (or that we detect changes and update the MSRV).

Add build on MSRV 1.54.0 in CI

---

tests/protocol.rs

Added strict encoding and decoding tests on protocol messages.

Test ser/de strict encoding on protocol messages

---

.github/workflows/release-to-crates-io.yml

The workflow disappeared from the list.

Still trying to fix release to crates.io

---

.github/workflows/create-release.yml
.github/workflows/release-to-crates-io.yml

change strategy, publish after creating release and handle manual release

Update strategy to publish on crates.io

---

CHANGELOG.md
Cargo.toml
src/blockchain.rs

Fix #179
Add lowercase variants for network FromStr impl.

Improve variants for parsing network

---

CHANGELOG.md
Cargo.toml
src/bitcoin/fee.rs
src/bitcoin/segwitv0.rs
src/bitcoin/segwitv0/buy.rs
src/bitcoin/segwitv0/cancel.rs
src/bitcoin/segwitv0/funding.rs
src/bitcoin/segwitv0/lock.rs
src/bitcoin/segwitv0/punish.rs
src/bitcoin/segwitv0/refund.rs
src/bitcoin/taproot/mod.rs
src/bitcoin/transaction.rs
src/crypto/slip10.rs
src/negotiation.rs
src/swap/btcxmr.rs
tests/negotiation.rs
tests/protocol.rs
tests/rpc/mod.rs

Update bitcoin to `bitcoin = "0.28.0-rc.1"` and other dependencies.

Update bitcoin and deps

---

CHANGELOG.md
README.md

Update README badge and document change in changelog.

Update MSRV badge

---

CHANGELOG.md
Cargo.toml
src/bitcoin/fee.rs
src/bitcoin/segwitv0.rs
src/bitcoin/segwitv0/buy.rs
src/bitcoin/segwitv0/cancel.rs
src/bitcoin/segwitv0/funding.rs
src/bitcoin/segwitv0/lock.rs
src/bitcoin/segwitv0/punish.rs
src/bitcoin/segwitv0/refund.rs
src/bitcoin/taproot/mod.rs
src/bitcoin/transaction.rs
src/crypto/slip10.rs
src/negotiation.rs
src/swap/btcxmr.rs
tests/negotiation.rs
tests/protocol.rs
tests/rpc/mod.rs

Revert lnp/bp dependency bump while https://github.com/farcaster-project/farcaster-node/pull/404 is blocked by https://github.com/LNP-WG/lnp-node/issues/50 so that we can continue testing/implementing/debugging other features in the meantime.

Revert dependency bump

---

Cargo.toml

Bump lightning encoding dep

---

Cargo.toml

Reverts farcaster-project/farcaster-core#230

Revert "Bump lightning encoding dep"

---

src/blockchain.rs

feat(blockchain-network): convert bitcoin::Network to Network

---

src/transaction.rs

Fix #155, fix #196
Improve logs in node with new Display implementation for txlabel.

feat!: tx label display and getters

---

Cargo.toml
src/crypto/dleq.rs

refactor: remove direct dep on bitcoin_hashes and use bitcoin instead

---

Cargo.toml
src/blockchain.rs
src/lib.rs

Closes #180 
Add all derivations and implementation to drop `Coin` in node in favor of `Blockchain`.

feat: implement necessary traits to replace Coin with Blockchain in node

---

CHANGELOG.md
README.md
src/blockchain.rs
src/consensus.rs
src/crypto.rs
src/lib.rs
src/protocol.rs
src/role.rs
src/swap/btcxmr.rs
src/swap/btcxmr/message.rs

Fix #262
Update
- crate's documentation
- readme
- changelog

chore: prepare release 0.5.0

---

README.md
RELEASING.md

Just some things that my eyes caught during reading.

docs: fix some typos and improve wording a bit (README.md and RELEASING.md)

---

README.md

See https://github.com/badges/shields/issues/8671 for more details

Chore: fix shields badge url

---

CHANGELOG.md
src/protocol.rs

Small adjustments to the main protocol documentation.

Doc: improve protocol function explanation
